[package]
name = "vehicle-dynamics"
version = "0.1.0"
edition = "2021"
authors = ["Devdutt Shenoi <devdutt@outlook.in>"]

[dependencies]
rand = "0.8.5"
serde = "1"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread", "time"] }
